### ISSUE TITLE
No method created_at for Delayed::Backend::Ironmq::Job

### ISSUE THREAD

**Issue by nerdyworm** [iron-io/delayed_job_ironmq#19]
Hello friends!

We have hit a small snag with your delayed job adapter.  It seems that our exception tracking library is looking for a created_at method on the Delayed::Backend::Ironmq::Job class.

Source of issue:
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/delayed_job.rb#L33

Let me know if you need any other information.

Thanks!

**Comment by treeder** [comment]
Can you put this git repo in your Gemfile to use the latest from master and try it out? Added that field.

**Comment by nerdyworm** [comment]
Forgot to mention we were on the v3 branch.  

Tested the fix with: https://github.com/iron-io/delayed_job_ironmq/pull/20

Everything is behaving properly with the addition of the comma :)

**Comment by treeder** [comment]
Oops. ;)
